//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class EventData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DebutField;
        
        private System.DateTime FinField;
        
        private string LieuField;
        
        private string MatiereField;
        
        private string NomField;
        
        private bool ObligatoireField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Debut
        {
            get
            {
                return this.DebutField;
            }
            set
            {
                this.DebutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fin
        {
            get
            {
                return this.FinField;
            }
            set
            {
                this.FinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lieu
        {
            get
            {
                return this.LieuField;
            }
            set
            {
                this.LieuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matiere
        {
            get
            {
                return this.MatiereField;
            }
            set
            {
                this.MatiereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Obligatoire
        {
            get
            {
                return this.ObligatoireField;
            }
            set
            {
                this.ObligatoireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBusinessLayer")]
public interface IBusinessLayer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getEventsData_Campus", ReplyAction="http://tempuri.org/IBusinessLayer/getEventsData_CampusResponse")]
    Client.EventData[] getEventsData_Campus(string CampusName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getEventsData_University", ReplyAction="http://tempuri.org/IBusinessLayer/getEventsData_UniversityResponse")]
    Client.EventData[] getEventsData_University(System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getEventsData_Periode", ReplyAction="http://tempuri.org/IBusinessLayer/getEventsData_PeriodeResponse")]
    Client.EventData[] getEventsData_Periode(string PromoPeriodeName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getEventsData_Class", ReplyAction="http://tempuri.org/IBusinessLayer/getEventsData_ClassResponse")]
    Client.EventData[] getEventsData_Class(string ClassName, string CampusName, string PromoPeriodeName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IBusinessLayerChannel : IBusinessLayer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BusinessLayerClient : System.ServiceModel.ClientBase<IBusinessLayer>, IBusinessLayer
{
    
    public BusinessLayerClient()
    {
    }
    
    public BusinessLayerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BusinessLayerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BusinessLayerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BusinessLayerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Client.EventData[] getEventsData_Campus(string CampusName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate)
    {
        return base.Channel.getEventsData_Campus(CampusName, Start, Stop, LastUpdate);
    }
    
    public Client.EventData[] getEventsData_University(System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate)
    {
        return base.Channel.getEventsData_University(Start, Stop, LastUpdate);
    }
    
    public Client.EventData[] getEventsData_Periode(string PromoPeriodeName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate)
    {
        return base.Channel.getEventsData_Periode(PromoPeriodeName, Start, Stop, LastUpdate);
    }
    
    public Client.EventData[] getEventsData_Class(string ClassName, string CampusName, string PromoPeriodeName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate)
    {
        return base.Channel.getEventsData_Class(ClassName, CampusName, PromoPeriodeName, Start, Stop, LastUpdate);
    }
}
