//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BusinessService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdName", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.BusinessService.ClassData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.BusinessService.PeriodData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.BusinessService.SubjectData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.BusinessService.ModalityData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.BusinessService.UserData))]
    public partial class IdName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class ClassData : Client.BusinessService.IdName {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.BusinessService.IdName CampusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.BusinessService.IdName PeriodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.BusinessService.IdName Campus {
            get {
                return this.CampusField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusField, value) != true)) {
                    this.CampusField = value;
                    this.RaisePropertyChanged("Campus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.BusinessService.IdName Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodField, value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class PeriodData : Client.BusinessService.IdName {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromotionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromotionName {
            get {
                return this.PromotionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PromotionNameField, value) != true)) {
                    this.PromotionNameField = value;
                    this.RaisePropertyChanged("PromotionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubjectData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class SubjectData : Client.BusinessService.IdName {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.BusinessService.ModalityData[] ModalitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModalityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hours {
            get {
                return this.HoursField;
            }
            set {
                if ((this.HoursField.Equals(value) != true)) {
                    this.HoursField = value;
                    this.RaisePropertyChanged("Hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.BusinessService.ModalityData[] Modalities {
            get {
                return this.ModalitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ModalitiesField, value) != true)) {
                    this.ModalitiesField = value;
                    this.RaisePropertyChanged("Modalities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modality {
            get {
                return this.ModalityField;
            }
            set {
                if ((object.ReferenceEquals(this.ModalityField, value) != true)) {
                    this.ModalityField = value;
                    this.RaisePropertyChanged("Modality");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModalityData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class ModalityData : Client.BusinessService.IdName {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubjectIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hours {
            get {
                return this.HoursField;
            }
            set {
                if ((this.HoursField.Equals(value) != true)) {
                    this.HoursField = value;
                    this.RaisePropertyChanged("Hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubjectId {
            get {
                return this.SubjectIdField;
            }
            set {
                if ((this.SubjectIdField.Equals(value) != true)) {
                    this.SubjectIdField = value;
                    this.RaisePropertyChanged("SubjectId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class UserData : Client.BusinessService.IdName {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.BusinessService.IdName ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.BusinessService.IdName Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class RoleData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.BusinessService.RoleData.RoleType RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TargetIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.BusinessService.RoleData.RoleType Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TargetId {
            get {
                return this.TargetIdField;
            }
            set {
                if ((this.TargetIdField.Equals(value) != true)) {
                    this.TargetIdField = value;
                    this.RaisePropertyChanged("TargetId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="RoleData.RoleType", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
        public enum RoleType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Administrator = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CampusManager = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Speaker = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class EventData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MandatoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpeakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Client.BusinessService.EventData.TypeEnum> TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Mandatory {
            get {
                return this.MandatoryField;
            }
            set {
                if ((this.MandatoryField.Equals(value) != true)) {
                    this.MandatoryField = value;
                    this.RaisePropertyChanged("Mandatory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modality {
            get {
                return this.ModalityField;
            }
            set {
                if ((object.ReferenceEquals(this.ModalityField, value) != true)) {
                    this.ModalityField = value;
                    this.RaisePropertyChanged("Modality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Speaker {
            get {
                return this.SpeakerField;
            }
            set {
                if ((object.ReferenceEquals(this.SpeakerField, value) != true)) {
                    this.SpeakerField = value;
                    this.RaisePropertyChanged("Speaker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Client.BusinessService.EventData.TypeEnum> Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="EventData.TypeEnum", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
        public enum TypeEnum : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            University = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Campus = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Period = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Class = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            User = 4,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusinessService.IBusinessLayer")]
    public interface IBusinessLayer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/delUser", ReplyAction="http://tempuri.org/IBusinessLayer/delUserResponse")]
        string delUser(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/delClass", ReplyAction="http://tempuri.org/IBusinessLayer/delClassResponse")]
        string delClass(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/delSubject", ReplyAction="http://tempuri.org/IBusinessLayer/delSubjectResponse")]
        string delSubject(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/delPeriod", ReplyAction="http://tempuri.org/IBusinessLayer/delPeriodResponse")]
        string delPeriod(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/delRole", ReplyAction="http://tempuri.org/IBusinessLayer/delRoleResponse")]
        string delRole(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/delEvent", ReplyAction="http://tempuri.org/IBusinessLayer/delEventResponse")]
        string delEvent(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/delCampus", ReplyAction="http://tempuri.org/IBusinessLayer/delCampusResponse")]
        string delCampus(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/delPromotion", ReplyAction="http://tempuri.org/IBusinessLayer/delPromotionResponse")]
        string delPromotion(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getUser", ReplyAction="http://tempuri.org/IBusinessLayer/getUserResponse")]
        Client.BusinessService.UserData getUser(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getClass", ReplyAction="http://tempuri.org/IBusinessLayer/getClassResponse")]
        Client.BusinessService.ClassData getClass(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getPeriod", ReplyAction="http://tempuri.org/IBusinessLayer/getPeriodResponse")]
        Client.BusinessService.PeriodData getPeriod(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getUserRoles", ReplyAction="http://tempuri.org/IBusinessLayer/getUserRolesResponse")]
        Client.BusinessService.RoleData[] getUserRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getEvents", ReplyAction="http://tempuri.org/IBusinessLayer/getEventsResponse")]
        Client.BusinessService.EventData[] getEvents(int Planning, System.DateTime Start, System.DateTime Stop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getSpeakerEvents", ReplyAction="http://tempuri.org/IBusinessLayer/getSpeakerEventsResponse")]
        Client.BusinessService.EventData[] getSpeakerEvents(int ID, System.DateTime Start, System.DateTime Stop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/isPlanningUpToDate", ReplyAction="http://tempuri.org/IBusinessLayer/isPlanningUpToDateResponse")]
        bool isPlanningUpToDate(int Planning, System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getPlannings", ReplyAction="http://tempuri.org/IBusinessLayer/getPlanningsResponse")]
        Client.BusinessService.IdName[] getPlannings(Client.BusinessService.EventData.TypeEnum Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getUniversity", ReplyAction="http://tempuri.org/IBusinessLayer/getUniversityResponse")]
        Client.BusinessService.IdName getUniversity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getUsers", ReplyAction="http://tempuri.org/IBusinessLayer/getUsersResponse")]
        Client.BusinessService.IdName[] getUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getPromotions", ReplyAction="http://tempuri.org/IBusinessLayer/getPromotionsResponse")]
        Client.BusinessService.IdName[] getPromotions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getSubjects", ReplyAction="http://tempuri.org/IBusinessLayer/getSubjectsResponse")]
        Client.BusinessService.SubjectData[] getSubjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getSpeakers", ReplyAction="http://tempuri.org/IBusinessLayer/getSpeakersResponse")]
        Client.BusinessService.IdName[] getSpeakers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getCampusPeriodClassTree", ReplyAction="http://tempuri.org/IBusinessLayer/getCampusPeriodClassTreeResponse")]
        System.Collections.Generic.Dictionary<Client.BusinessService.IdName, System.Collections.Generic.Dictionary<Client.BusinessService.IdName, Client.BusinessService.IdName[]>> getCampusPeriodClassTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addUser", ReplyAction="http://tempuri.org/IBusinessLayer/addUserResponse")]
        string addUser(Client.BusinessService.UserData User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addCampus", ReplyAction="http://tempuri.org/IBusinessLayer/addCampusResponse")]
        string addCampus(string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addClass", ReplyAction="http://tempuri.org/IBusinessLayer/addClassResponse")]
        string addClass(Client.BusinessService.ClassData Class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addPromotion", ReplyAction="http://tempuri.org/IBusinessLayer/addPromotionResponse")]
        string addPromotion(string PromotionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addSubject", ReplyAction="http://tempuri.org/IBusinessLayer/addSubjectResponse")]
        string addSubject(Client.BusinessService.SubjectData Subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addPeriod", ReplyAction="http://tempuri.org/IBusinessLayer/addPeriodResponse")]
        string addPeriod(Client.BusinessService.PeriodData Period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/grantRole", ReplyAction="http://tempuri.org/IBusinessLayer/grantRoleResponse")]
        string grantRole(int UserId, System.Nullable<int> Target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addEvent", ReplyAction="http://tempuri.org/IBusinessLayer/addEventResponse")]
        string addEvent(Client.BusinessService.EventData Event, int PlanningId, System.Nullable<int> SpeakerId, System.Nullable<int> Modality);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addPrivateEvent", ReplyAction="http://tempuri.org/IBusinessLayer/addPrivateEventResponse")]
        string addPrivateEvent(Client.BusinessService.EventData Event);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/setUser", ReplyAction="http://tempuri.org/IBusinessLayer/setUserResponse")]
        string setUser(Client.BusinessService.UserData UD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/setCampus", ReplyAction="http://tempuri.org/IBusinessLayer/setCampusResponse")]
        string setCampus(int Id, string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/setClass", ReplyAction="http://tempuri.org/IBusinessLayer/setClassResponse")]
        string setClass(Client.BusinessService.ClassData CD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/setPromotion", ReplyAction="http://tempuri.org/IBusinessLayer/setPromotionResponse")]
        string setPromotion(int Id, string PromotionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/setSubject", ReplyAction="http://tempuri.org/IBusinessLayer/setSubjectResponse")]
        string setSubject(Client.BusinessService.SubjectData SD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/setPeriod", ReplyAction="http://tempuri.org/IBusinessLayer/setPeriodResponse")]
        string setPeriod(Client.BusinessService.PeriodData PD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/setEvent", ReplyAction="http://tempuri.org/IBusinessLayer/setEventResponse")]
        string setEvent(Client.BusinessService.EventData EditedEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/setPrivateEvent", ReplyAction="http://tempuri.org/IBusinessLayer/setPrivateEventResponse")]
        string setPrivateEvent(Client.BusinessService.EventData EditedEvent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusinessLayerChannel : Client.BusinessService.IBusinessLayer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessLayerClient : System.ServiceModel.ClientBase<Client.BusinessService.IBusinessLayer>, Client.BusinessService.IBusinessLayer {
        
        public BusinessLayerClient() {
        }
        
        public BusinessLayerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessLayerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessLayerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessLayerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string delUser(int Id) {
            return base.Channel.delUser(Id);
        }
        
        public string delClass(int Id) {
            return base.Channel.delClass(Id);
        }
        
        public string delSubject(int Id) {
            return base.Channel.delSubject(Id);
        }
        
        public string delPeriod(int Id) {
            return base.Channel.delPeriod(Id);
        }
        
        public string delRole(int Id) {
            return base.Channel.delRole(Id);
        }
        
        public string delEvent(int Id) {
            return base.Channel.delEvent(Id);
        }
        
        public string delCampus(int Id) {
            return base.Channel.delCampus(Id);
        }
        
        public string delPromotion(int Id) {
            return base.Channel.delPromotion(Id);
        }
        
        public Client.BusinessService.UserData getUser(int ID) {
            return base.Channel.getUser(ID);
        }
        
        public Client.BusinessService.ClassData getClass(int ID) {
            return base.Channel.getClass(ID);
        }
        
        public Client.BusinessService.PeriodData getPeriod(int ID) {
            return base.Channel.getPeriod(ID);
        }
        
        public Client.BusinessService.RoleData[] getUserRoles() {
            return base.Channel.getUserRoles();
        }
        
        public Client.BusinessService.EventData[] getEvents(int Planning, System.DateTime Start, System.DateTime Stop) {
            return base.Channel.getEvents(Planning, Start, Stop);
        }
        
        public Client.BusinessService.EventData[] getSpeakerEvents(int ID, System.DateTime Start, System.DateTime Stop) {
            return base.Channel.getSpeakerEvents(ID, Start, Stop);
        }
        
        public bool isPlanningUpToDate(int Planning, System.DateTime LastUpdate) {
            return base.Channel.isPlanningUpToDate(Planning, LastUpdate);
        }
        
        public Client.BusinessService.IdName[] getPlannings(Client.BusinessService.EventData.TypeEnum Type) {
            return base.Channel.getPlannings(Type);
        }
        
        public Client.BusinessService.IdName getUniversity() {
            return base.Channel.getUniversity();
        }
        
        public Client.BusinessService.IdName[] getUsers() {
            return base.Channel.getUsers();
        }
        
        public Client.BusinessService.IdName[] getPromotions() {
            return base.Channel.getPromotions();
        }
        
        public Client.BusinessService.SubjectData[] getSubjects() {
            return base.Channel.getSubjects();
        }
        
        public Client.BusinessService.IdName[] getSpeakers() {
            return base.Channel.getSpeakers();
        }
        
        public System.Collections.Generic.Dictionary<Client.BusinessService.IdName, System.Collections.Generic.Dictionary<Client.BusinessService.IdName, Client.BusinessService.IdName[]>> getCampusPeriodClassTree() {
            return base.Channel.getCampusPeriodClassTree();
        }
        
        public string addUser(Client.BusinessService.UserData User) {
            return base.Channel.addUser(User);
        }
        
        public string addCampus(string CampusName) {
            return base.Channel.addCampus(CampusName);
        }
        
        public string addClass(Client.BusinessService.ClassData Class) {
            return base.Channel.addClass(Class);
        }
        
        public string addPromotion(string PromotionName) {
            return base.Channel.addPromotion(PromotionName);
        }
        
        public string addSubject(Client.BusinessService.SubjectData Subject) {
            return base.Channel.addSubject(Subject);
        }
        
        public string addPeriod(Client.BusinessService.PeriodData Period) {
            return base.Channel.addPeriod(Period);
        }
        
        public string grantRole(int UserId, System.Nullable<int> Target) {
            return base.Channel.grantRole(UserId, Target);
        }
        
        public string addEvent(Client.BusinessService.EventData Event, int PlanningId, System.Nullable<int> SpeakerId, System.Nullable<int> Modality) {
            return base.Channel.addEvent(Event, PlanningId, SpeakerId, Modality);
        }
        
        public string addPrivateEvent(Client.BusinessService.EventData Event) {
            return base.Channel.addPrivateEvent(Event);
        }
        
        public string setUser(Client.BusinessService.UserData UD) {
            return base.Channel.setUser(UD);
        }
        
        public string setCampus(int Id, string CampusName) {
            return base.Channel.setCampus(Id, CampusName);
        }
        
        public string setClass(Client.BusinessService.ClassData CD) {
            return base.Channel.setClass(CD);
        }
        
        public string setPromotion(int Id, string PromotionName) {
            return base.Channel.setPromotion(Id, PromotionName);
        }
        
        public string setSubject(Client.BusinessService.SubjectData SD) {
            return base.Channel.setSubject(SD);
        }
        
        public string setPeriod(Client.BusinessService.PeriodData PD) {
            return base.Channel.setPeriod(PD);
        }
        
        public string setEvent(Client.BusinessService.EventData EditedEvent) {
            return base.Channel.setEvent(EditedEvent);
        }
        
        public string setPrivateEvent(Client.BusinessService.EventData EditedEvent) {
            return base.Channel.setPrivateEvent(EditedEvent);
        }
    }
}
