//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BusinessLayer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class EventData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MandatoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpeakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Mandatory {
            get {
                return this.MandatoryField;
            }
            set {
                if ((this.MandatoryField.Equals(value) != true)) {
                    this.MandatoryField = value;
                    this.RaisePropertyChanged("Mandatory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modality {
            get {
                return this.ModalityField;
            }
            set {
                if ((object.ReferenceEquals(this.ModalityField, value) != true)) {
                    this.ModalityField = value;
                    this.RaisePropertyChanged("Modality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Speaker {
            get {
                return this.SpeakerField;
            }
            set {
                if ((object.ReferenceEquals(this.SpeakerField, value) != true)) {
                    this.SpeakerField = value;
                    this.RaisePropertyChanged("Speaker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusinessLayer.IBusinessService")]
    public interface IBusinessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addEventToPeriode", ReplyAction="http://tempuri.org/IBusinessService/addEventToPeriodeResponse")]
        string addEventToPeriode(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string PeriodeName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addEventToClass", ReplyAction="http://tempuri.org/IBusinessService/addEventToClassResponse")]
        string addEventToClass(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string ClassName, string Subject, string Modality, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addEventToUniversity", ReplyAction="http://tempuri.org/IBusinessService/addEventToUniversityResponse")]
        string addEventToUniversity(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addEventToUser", ReplyAction="http://tempuri.org/IBusinessService/addEventToUserResponse")]
        string addEventToUser(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setUser", ReplyAction="http://tempuri.org/IBusinessService/setUserResponse")]
        System.Tuple<string> setUser(string UserName, string UserPassword, string UserClassName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setCampus", ReplyAction="http://tempuri.org/IBusinessService/setCampusResponse")]
        string setCampus(string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setClass", ReplyAction="http://tempuri.org/IBusinessService/setClassResponse")]
        string setClass(string ClassName, string CampusName, string PeriodeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setPromotion", ReplyAction="http://tempuri.org/IBusinessService/setPromotionResponse")]
        string setPromotion(string PromotionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setSubject", ReplyAction="http://tempuri.org/IBusinessService/setSubjectResponse")]
        string setSubject(string SubjectName, int Hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setPeriod", ReplyAction="http://tempuri.org/IBusinessService/setPeriodResponse")]
        string setPeriod(string PeriodName, string PromotionName, System.DateTime PeriodStart, System.DateTime PeriodEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setEventToCampus", ReplyAction="http://tempuri.org/IBusinessService/setEventToCampusResponse")]
        string setEventToCampus(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string CampusName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setEventToPeriode", ReplyAction="http://tempuri.org/IBusinessService/setEventToPeriodeResponse")]
        string setEventToPeriode(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string PeriodeName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setEventToClass", ReplyAction="http://tempuri.org/IBusinessService/setEventToClassResponse")]
        string setEventToClass(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string ClassName, string Subject, string Modality, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setEventToUniversity", ReplyAction="http://tempuri.org/IBusinessService/setEventToUniversityResponse")]
        string setEventToUniversity(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setEventToUser", ReplyAction="http://tempuri.org/IBusinessService/setEventToUserResponse")]
        string setEventToUser(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delUser", ReplyAction="http://tempuri.org/IBusinessService/delUserResponse")]
        string delUser(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delCampus", ReplyAction="http://tempuri.org/IBusinessService/delCampusResponse")]
        string delCampus(string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delClass", ReplyAction="http://tempuri.org/IBusinessService/delClassResponse")]
        string delClass(string ClassName, string CampusName, string PeriodeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delPromotion", ReplyAction="http://tempuri.org/IBusinessService/delPromotionResponse")]
        string delPromotion(string PromotionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delSubject", ReplyAction="http://tempuri.org/IBusinessService/delSubjectResponse")]
        string delSubject(string SubjectName, int Hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delPeriod", ReplyAction="http://tempuri.org/IBusinessService/delPeriodResponse")]
        string delPeriod(string PeriodName, string PromotionName, System.DateTime PeriodStart, System.DateTime PeriodEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delRight", ReplyAction="http://tempuri.org/IBusinessService/delRightResponse")]
        string delRight(string UserName, string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delEventToCampus", ReplyAction="http://tempuri.org/IBusinessService/delEventToCampusResponse")]
        string delEventToCampus(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string CampusName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delEventToPeriode", ReplyAction="http://tempuri.org/IBusinessService/delEventToPeriodeResponse")]
        string delEventToPeriode(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string PeriodeName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delEventToClass", ReplyAction="http://tempuri.org/IBusinessService/delEventToClassResponse")]
        string delEventToClass(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string ClassName, string Subject, string Modality, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delEventToUniversity", ReplyAction="http://tempuri.org/IBusinessService/delEventToUniversityResponse")]
        string delEventToUniversity(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delEventToUser", ReplyAction="http://tempuri.org/IBusinessService/delEventToUserResponse")]
        string delEventToUser(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getEventsByCampus", ReplyAction="http://tempuri.org/IBusinessService/getEventsByCampusResponse")]
        Client.BusinessLayer.EventData[] getEventsByCampus(string CampusName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getEventsByUniversity", ReplyAction="http://tempuri.org/IBusinessService/getEventsByUniversityResponse")]
        Client.BusinessLayer.EventData[] getEventsByUniversity(System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getEventsByPeriod", ReplyAction="http://tempuri.org/IBusinessService/getEventsByPeriodResponse")]
        Client.BusinessLayer.EventData[] getEventsByPeriod(string PeriodName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getEventsByClass", ReplyAction="http://tempuri.org/IBusinessService/getEventsByClassResponse")]
        Client.BusinessLayer.EventData[] getEventsByClass(string ClassName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getPrivateEvents", ReplyAction="http://tempuri.org/IBusinessService/getPrivateEventsResponse")]
        Client.BusinessLayer.EventData[] getPrivateEvents(System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getCampusNames", ReplyAction="http://tempuri.org/IBusinessService/getCampusNamesResponse")]
        string[] getCampusNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getClassesNames", ReplyAction="http://tempuri.org/IBusinessService/getClassesNamesResponse")]
        string[] getClassesNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getPromotionsNames", ReplyAction="http://tempuri.org/IBusinessService/getPromotionsNamesResponse")]
        string[] getPromotionsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getPeriodsNames", ReplyAction="http://tempuri.org/IBusinessService/getPeriodsNamesResponse")]
        string[] getPeriodsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getSubjectsNames", ReplyAction="http://tempuri.org/IBusinessService/getSubjectsNamesResponse")]
        string[] getSubjectsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getUsersNames", ReplyAction="http://tempuri.org/IBusinessService/getUsersNamesResponse")]
        string[] getUsersNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getModalities", ReplyAction="http://tempuri.org/IBusinessService/getModalitiesResponse")]
        string[] getModalities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getCampusPeriodClassTree", ReplyAction="http://tempuri.org/IBusinessService/getCampusPeriodClassTreeResponse")]
        System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, string[]>> getCampusPeriodClassTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdCampusNames", ReplyAction="http://tempuri.org/IBusinessService/getIdCampusNamesResponse")]
        System.Tuple<int, string>[] getIdCampusNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdClassesNames", ReplyAction="http://tempuri.org/IBusinessService/getIdClassesNamesResponse")]
        System.Tuple<int, string>[] getIdClassesNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdPromotionsNames", ReplyAction="http://tempuri.org/IBusinessService/getIdPromotionsNamesResponse")]
        System.Tuple<int, string>[] getIdPromotionsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdPeriodsNames", ReplyAction="http://tempuri.org/IBusinessService/getIdPeriodsNamesResponse")]
        System.Tuple<int, string>[] getIdPeriodsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdSubjectsNamesModality", ReplyAction="http://tempuri.org/IBusinessService/getIdSubjectsNamesModalityResponse")]
        System.Tuple<int, string, string>[] getIdSubjectsNamesModality();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdUsersNames", ReplyAction="http://tempuri.org/IBusinessService/getIdUsersNamesResponse")]
        System.Tuple<int, string>[] getIdUsersNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdCampusPeriodClassTree", ReplyAction="http://tempuri.org/IBusinessService/getIdCampusPeriodClassTreeResponse")]
        System.Collections.Generic.Dictionary<System.Tuple<int, string>, System.Collections.Generic.Dictionary<System.Tuple<int, string>, System.Tuple<int, string>[]>> getIdCampusPeriodClassTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addUser", ReplyAction="http://tempuri.org/IBusinessService/addUserResponse")]
        string addUser(string UserName, string UserPassword, string UserClassName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addCampus", ReplyAction="http://tempuri.org/IBusinessService/addCampusResponse")]
        string addCampus(string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addClass", ReplyAction="http://tempuri.org/IBusinessService/addClassResponse")]
        string addClass(string ClassName, string CampusName, string PeriodeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addPromotion", ReplyAction="http://tempuri.org/IBusinessService/addPromotionResponse")]
        string addPromotion(string PromotionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addSubject", ReplyAction="http://tempuri.org/IBusinessService/addSubjectResponse")]
        string addSubject(string SubjectName, int Hours, string Modality);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addPeriod", ReplyAction="http://tempuri.org/IBusinessService/addPeriodResponse")]
        string addPeriod(string PeriodName, string PromotionName, System.DateTime PeriodStart, System.DateTime PeriodEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/grantNewRight", ReplyAction="http://tempuri.org/IBusinessService/grantNewRightResponse")]
        string grantNewRight(string UserName, string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addEventToCampus", ReplyAction="http://tempuri.org/IBusinessService/addEventToCampusResponse")]
        string addEventToCampus(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string CampusName, string Place);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusinessServiceChannel : Client.BusinessLayer.IBusinessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessServiceClient : System.ServiceModel.ClientBase<Client.BusinessLayer.IBusinessService>, Client.BusinessLayer.IBusinessService {
        
        public BusinessServiceClient() {
        }
        
        public BusinessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addEventToPeriode(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string PeriodeName, string Place) {
            return base.Channel.addEventToPeriode(EventName, Start, End, Mandatory, SpeakerName, PeriodeName, Place);
        }
        
        public string addEventToClass(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string ClassName, string Subject, string Modality, string Place) {
            return base.Channel.addEventToClass(EventName, Start, End, Mandatory, SpeakerName, ClassName, Subject, Modality, Place);
        }
        
        public string addEventToUniversity(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string Place) {
            return base.Channel.addEventToUniversity(EventName, Start, End, Mandatory, SpeakerName, Place);
        }
        
        public string addEventToUser(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string Place) {
            return base.Channel.addEventToUser(EventName, Start, End, Mandatory, Place);
        }
        
        public System.Tuple<string> setUser(string UserName, string UserPassword, string UserClassName) {
            return base.Channel.setUser(UserName, UserPassword, UserClassName);
        }
        
        public string setCampus(string CampusName) {
            return base.Channel.setCampus(CampusName);
        }
        
        public string setClass(string ClassName, string CampusName, string PeriodeName) {
            return base.Channel.setClass(ClassName, CampusName, PeriodeName);
        }
        
        public string setPromotion(string PromotionName) {
            return base.Channel.setPromotion(PromotionName);
        }
        
        public string setSubject(string SubjectName, int Hours) {
            return base.Channel.setSubject(SubjectName, Hours);
        }
        
        public string setPeriod(string PeriodName, string PromotionName, System.DateTime PeriodStart, System.DateTime PeriodEnd) {
            return base.Channel.setPeriod(PeriodName, PromotionName, PeriodStart, PeriodEnd);
        }
        
        public string setEventToCampus(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string CampusName, string Place) {
            return base.Channel.setEventToCampus(EventName, Start, End, Mandatory, SpeakerName, CampusName, Place);
        }
        
        public string setEventToPeriode(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string PeriodeName, string Place) {
            return base.Channel.setEventToPeriode(EventName, Start, End, Mandatory, SpeakerName, PeriodeName, Place);
        }
        
        public string setEventToClass(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string ClassName, string Subject, string Modality, string Place) {
            return base.Channel.setEventToClass(EventName, Start, End, Mandatory, SpeakerName, ClassName, Subject, Modality, Place);
        }
        
        public string setEventToUniversity(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string Place) {
            return base.Channel.setEventToUniversity(EventName, Start, End, Mandatory, SpeakerName, Place);
        }
        
        public string setEventToUser(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string Place) {
            return base.Channel.setEventToUser(EventName, Start, End, Mandatory, Place);
        }
        
        public string delUser(string UserName) {
            return base.Channel.delUser(UserName);
        }
        
        public string delCampus(string CampusName) {
            return base.Channel.delCampus(CampusName);
        }
        
        public string delClass(string ClassName, string CampusName, string PeriodeName) {
            return base.Channel.delClass(ClassName, CampusName, PeriodeName);
        }
        
        public string delPromotion(string PromotionName) {
            return base.Channel.delPromotion(PromotionName);
        }
        
        public string delSubject(string SubjectName, int Hours) {
            return base.Channel.delSubject(SubjectName, Hours);
        }
        
        public string delPeriod(string PeriodName, string PromotionName, System.DateTime PeriodStart, System.DateTime PeriodEnd) {
            return base.Channel.delPeriod(PeriodName, PromotionName, PeriodStart, PeriodEnd);
        }
        
        public string delRight(string UserName, string CampusName) {
            return base.Channel.delRight(UserName, CampusName);
        }
        
        public string delEventToCampus(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string CampusName, string Place) {
            return base.Channel.delEventToCampus(EventName, Start, End, Mandatory, SpeakerName, CampusName, Place);
        }
        
        public string delEventToPeriode(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string PeriodeName, string Place) {
            return base.Channel.delEventToPeriode(EventName, Start, End, Mandatory, SpeakerName, PeriodeName, Place);
        }
        
        public string delEventToClass(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string ClassName, string Subject, string Modality, string Place) {
            return base.Channel.delEventToClass(EventName, Start, End, Mandatory, SpeakerName, ClassName, Subject, Modality, Place);
        }
        
        public string delEventToUniversity(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string Place) {
            return base.Channel.delEventToUniversity(EventName, Start, End, Mandatory, SpeakerName, Place);
        }
        
        public string delEventToUser(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string Place) {
            return base.Channel.delEventToUser(EventName, Start, End, Mandatory, Place);
        }
        
        public Client.BusinessLayer.EventData[] getEventsByCampus(string CampusName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate) {
            return base.Channel.getEventsByCampus(CampusName, Start, Stop, LastUpdate);
        }
        
        public Client.BusinessLayer.EventData[] getEventsByUniversity(System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate) {
            return base.Channel.getEventsByUniversity(Start, Stop, LastUpdate);
        }
        
        public Client.BusinessLayer.EventData[] getEventsByPeriod(string PeriodName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate) {
            return base.Channel.getEventsByPeriod(PeriodName, Start, Stop, LastUpdate);
        }
        
        public Client.BusinessLayer.EventData[] getEventsByClass(string ClassName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate) {
            return base.Channel.getEventsByClass(ClassName, Start, Stop, LastUpdate);
        }
        
        public Client.BusinessLayer.EventData[] getPrivateEvents(System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate) {
            return base.Channel.getPrivateEvents(Start, Stop, LastUpdate);
        }
        
        public string[] getCampusNames() {
            return base.Channel.getCampusNames();
        }
        
        public string[] getClassesNames() {
            return base.Channel.getClassesNames();
        }
        
        public string[] getPromotionsNames() {
            return base.Channel.getPromotionsNames();
        }
        
        public string[] getPeriodsNames() {
            return base.Channel.getPeriodsNames();
        }
        
        public string[] getSubjectsNames() {
            return base.Channel.getSubjectsNames();
        }
        
        public string[] getUsersNames() {
            return base.Channel.getUsersNames();
        }
        
        public string[] getModalities() {
            return base.Channel.getModalities();
        }
        
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, string[]>> getCampusPeriodClassTree() {
            return base.Channel.getCampusPeriodClassTree();
        }
        
        public System.Tuple<int, string>[] getIdCampusNames() {
            return base.Channel.getIdCampusNames();
        }
        
        public System.Tuple<int, string>[] getIdClassesNames() {
            return base.Channel.getIdClassesNames();
        }
        
        public System.Tuple<int, string>[] getIdPromotionsNames() {
            return base.Channel.getIdPromotionsNames();
        }
        
        public System.Tuple<int, string>[] getIdPeriodsNames() {
            return base.Channel.getIdPeriodsNames();
        }
        
        public System.Tuple<int, string, string>[] getIdSubjectsNamesModality() {
            return base.Channel.getIdSubjectsNamesModality();
        }
        
        public System.Tuple<int, string>[] getIdUsersNames() {
            return base.Channel.getIdUsersNames();
        }
        
        public System.Collections.Generic.Dictionary<System.Tuple<int, string>, System.Collections.Generic.Dictionary<System.Tuple<int, string>, System.Tuple<int, string>[]>> getIdCampusPeriodClassTree() {
            return base.Channel.getIdCampusPeriodClassTree();
        }
        
        public string addUser(string UserName, string UserPassword, string UserClassName) {
            return base.Channel.addUser(UserName, UserPassword, UserClassName);
        }
        
        public string addCampus(string CampusName) {
            return base.Channel.addCampus(CampusName);
        }
        
        public string addClass(string ClassName, string CampusName, string PeriodeName) {
            return base.Channel.addClass(ClassName, CampusName, PeriodeName);
        }
        
        public string addPromotion(string PromotionName) {
            return base.Channel.addPromotion(PromotionName);
        }
        
        public string addSubject(string SubjectName, int Hours, string Modality) {
            return base.Channel.addSubject(SubjectName, Hours, Modality);
        }
        
        public string addPeriod(string PeriodName, string PromotionName, System.DateTime PeriodStart, System.DateTime PeriodEnd) {
            return base.Channel.addPeriod(PeriodName, PromotionName, PeriodStart, PeriodEnd);
        }
        
        public string grantNewRight(string UserName, string CampusName) {
            return base.Channel.grantNewRight(UserName, CampusName);
        }
        
        public string addEventToCampus(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string CampusName, string Place) {
            return base.Channel.addEventToCampus(EventName, Start, End, Mandatory, SpeakerName, CampusName, Place);
        }
    }
}
