//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class EventData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime EndField;
        
        private bool MandatoryField;
        
        private string NameField;
        
        private string PlaceField;
        
        private string SpeakerField;
        
        private System.DateTime StartField;
        
        private string SubjectField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End
        {
            get
            {
                return this.EndField;
            }
            set
            {
                this.EndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Mandatory
        {
            get
            {
                return this.MandatoryField;
            }
            set
            {
                this.MandatoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place
        {
            get
            {
                return this.PlaceField;
            }
            set
            {
                this.PlaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Speaker
        {
            get
            {
                return this.SpeakerField;
            }
            set
            {
                this.SpeakerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start
        {
            get
            {
                return this.StartField;
            }
            set
            {
                this.StartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBusinessLayer")]
public interface IBusinessLayer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getEventsByCampus", ReplyAction="http://tempuri.org/IBusinessLayer/getEventsByCampusResponse")]
    BusinessLayer.EventData[] getEventsByCampus(string CampusName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getEventsByUniversity", ReplyAction="http://tempuri.org/IBusinessLayer/getEventsByUniversityResponse")]
    BusinessLayer.EventData[] getEventsByUniversity(System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getEventsByPeriod", ReplyAction="http://tempuri.org/IBusinessLayer/getEventsByPeriodResponse")]
    BusinessLayer.EventData[] getEventsByPeriod(string PeriodName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getEventsByClass", ReplyAction="http://tempuri.org/IBusinessLayer/getEventsByClassResponse")]
    BusinessLayer.EventData[] getEventsByClass(string ClassName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getPrivateEvents", ReplyAction="http://tempuri.org/IBusinessLayer/getPrivateEventsResponse")]
    BusinessLayer.EventData[] getPrivateEvents(System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getCampusNames", ReplyAction="http://tempuri.org/IBusinessLayer/getCampusNamesResponse")]
    string[] getCampusNames();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getClassesNames", ReplyAction="http://tempuri.org/IBusinessLayer/getClassesNamesResponse")]
    string[] getClassesNames();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getPromotionsNames", ReplyAction="http://tempuri.org/IBusinessLayer/getPromotionsNamesResponse")]
    string[] getPromotionsNames();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/getPeriodsNames", ReplyAction="http://tempuri.org/IBusinessLayer/getPeriodsNamesResponse")]
    string[] getPeriodsNames();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addUser", ReplyAction="http://tempuri.org/IBusinessLayer/addUserResponse")]
    string addUser(string UserName, string UserPassword, string UserClassName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addCampus", ReplyAction="http://tempuri.org/IBusinessLayer/addCampusResponse")]
    string addCampus(string CampusName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addClass", ReplyAction="http://tempuri.org/IBusinessLayer/addClassResponse")]
    string addClass(string ClassName, string CampusName, string PeriodeName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addPromotion", ReplyAction="http://tempuri.org/IBusinessLayer/addPromotionResponse")]
    string addPromotion(string PromotionName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addSubject", ReplyAction="http://tempuri.org/IBusinessLayer/addSubjectResponse")]
    string addSubject(string SubjectName, int Hours);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addPeriod", ReplyAction="http://tempuri.org/IBusinessLayer/addPeriodResponse")]
    string addPeriod(string PeriodName, string PromotionName, System.DateTime PeriodStart, System.DateTime PeriodEnd);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/grantNewRight", ReplyAction="http://tempuri.org/IBusinessLayer/grantNewRightResponse")]
    string grantNewRight(string UserName, int Type, string CampusName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessLayer/addEvent", ReplyAction="http://tempuri.org/IBusinessLayer/addEventResponse")]
    string addEvent(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string CampusName, string PeriodName, string SubjectName, string Type, string Place);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IBusinessLayerChannel : IBusinessLayer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BusinessLayerClient : System.ServiceModel.ClientBase<IBusinessLayer>, IBusinessLayer
{
    
    public BusinessLayerClient()
    {
    }
    
    public BusinessLayerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BusinessLayerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BusinessLayerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BusinessLayerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public BusinessLayer.EventData[] getEventsByCampus(string CampusName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate)
    {
        return base.Channel.getEventsByCampus(CampusName, Start, Stop, LastUpdate);
    }
    
    public BusinessLayer.EventData[] getEventsByUniversity(System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate)
    {
        return base.Channel.getEventsByUniversity(Start, Stop, LastUpdate);
    }
    
    public BusinessLayer.EventData[] getEventsByPeriod(string PeriodName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate)
    {
        return base.Channel.getEventsByPeriod(PeriodName, Start, Stop, LastUpdate);
    }
    
    public BusinessLayer.EventData[] getEventsByClass(string ClassName, System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate)
    {
        return base.Channel.getEventsByClass(ClassName, Start, Stop, LastUpdate);
    }
    
    public BusinessLayer.EventData[] getPrivateEvents(System.DateTime Start, System.DateTime Stop, System.DateTime LastUpdate)
    {
        return base.Channel.getPrivateEvents(Start, Stop, LastUpdate);
    }
    
    public string[] getCampusNames()
    {
        return base.Channel.getCampusNames();
    }
    
    public string[] getClassesNames()
    {
        return base.Channel.getClassesNames();
    }
    
    public string[] getPromotionsNames()
    {
        return base.Channel.getPromotionsNames();
    }
    
    public string[] getPeriodsNames()
    {
        return base.Channel.getPeriodsNames();
    }
    
    public string addUser(string UserName, string UserPassword, string UserClassName)
    {
        return base.Channel.addUser(UserName, UserPassword, UserClassName);
    }
    
    public string addCampus(string CampusName)
    {
        return base.Channel.addCampus(CampusName);
    }
    
    public string addClass(string ClassName, string CampusName, string PeriodeName)
    {
        return base.Channel.addClass(ClassName, CampusName, PeriodeName);
    }
    
    public string addPromotion(string PromotionName)
    {
        return base.Channel.addPromotion(PromotionName);
    }
    
    public string addSubject(string SubjectName, int Hours)
    {
        return base.Channel.addSubject(SubjectName, Hours);
    }
    
    public string addPeriod(string PeriodName, string PromotionName, System.DateTime PeriodStart, System.DateTime PeriodEnd)
    {
        return base.Channel.addPeriod(PeriodName, PromotionName, PeriodStart, PeriodEnd);
    }
    
    public string grantNewRight(string UserName, int Type, string CampusName)
    {
        return base.Channel.grantNewRight(UserName, Type, CampusName);
    }
    
    public string addEvent(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string CampusName, string PeriodName, string SubjectName, string Type, string Place)
    {
        return base.Channel.addEvent(EventName, Start, End, Mandatory, SpeakerName, CampusName, PeriodName, SubjectName, Type, Place);
    }
}
