//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BusinessLayer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClassIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampusName {
            get {
                return this.CampusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusNameField, value) != true)) {
                    this.CampusNameField = value;
                    this.RaisePropertyChanged("CampusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClassId {
            get {
                return this.ClassIdField;
            }
            set {
                if ((this.ClassIdField.Equals(value) != true)) {
                    this.ClassIdField = value;
                    this.RaisePropertyChanged("ClassId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class ClassData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampusName {
            get {
                return this.CampusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusNameField, value) != true)) {
                    this.CampusNameField = value;
                    this.RaisePropertyChanged("CampusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((this.PeriodField.Equals(value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubjectData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class SubjectData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hours {
            get {
                return this.HoursField;
            }
            set {
                if ((this.HoursField.Equals(value) != true)) {
                    this.HoursField = value;
                    this.RaisePropertyChanged("Hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modality {
            get {
                return this.ModalityField;
            }
            set {
                if ((object.ReferenceEquals(this.ModalityField, value) != true)) {
                    this.ModalityField = value;
                    this.RaisePropertyChanged("Modality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class PeriodData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromotionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromotionName {
            get {
                return this.PromotionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PromotionNameField, value) != true)) {
                    this.PromotionNameField = value;
                    this.RaisePropertyChanged("PromotionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventData", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class EventData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MandatoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpeakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Mandatory {
            get {
                return this.MandatoryField;
            }
            set {
                if ((this.MandatoryField.Equals(value) != true)) {
                    this.MandatoryField = value;
                    this.RaisePropertyChanged("Mandatory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modality {
            get {
                return this.ModalityField;
            }
            set {
                if ((object.ReferenceEquals(this.ModalityField, value) != true)) {
                    this.ModalityField = value;
                    this.RaisePropertyChanged("Modality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Speaker {
            get {
                return this.SpeakerField;
            }
            set {
                if ((object.ReferenceEquals(this.SpeakerField, value) != true)) {
                    this.SpeakerField = value;
                    this.RaisePropertyChanged("Speaker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdName", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class IdName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusinessLayer.IBusinessService")]
    public interface IBusinessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addPromotion", ReplyAction="http://tempuri.org/IBusinessService/addPromotionResponse")]
        string addPromotion(string PromotionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addSubject", ReplyAction="http://tempuri.org/IBusinessService/addSubjectResponse")]
        string addSubject(string SubjectName, int Hours, string Modality);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addPeriod", ReplyAction="http://tempuri.org/IBusinessService/addPeriodResponse")]
        string addPeriod(string PeriodName, string PromotionName, System.DateTime PeriodStart, System.DateTime PeriodEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/grantNewRight", ReplyAction="http://tempuri.org/IBusinessService/grantNewRightResponse")]
        string grantNewRight(string UserName, string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addEventToCampus", ReplyAction="http://tempuri.org/IBusinessService/addEventToCampusResponse")]
        string addEventToCampus(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string CampusName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addEventToPeriode", ReplyAction="http://tempuri.org/IBusinessService/addEventToPeriodeResponse")]
        string addEventToPeriode(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string PeriodeName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addEventToClass", ReplyAction="http://tempuri.org/IBusinessService/addEventToClassResponse")]
        string addEventToClass(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string ClassName, string Subject, string Modality, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addEventToUniversity", ReplyAction="http://tempuri.org/IBusinessService/addEventToUniversityResponse")]
        string addEventToUniversity(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addEventToUser", ReplyAction="http://tempuri.org/IBusinessService/addEventToUserResponse")]
        string addEventToUser(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string Place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setUser", ReplyAction="http://tempuri.org/IBusinessService/setUserResponse")]
        string setUser(Client.BusinessLayer.UserData UD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setCampus", ReplyAction="http://tempuri.org/IBusinessService/setCampusResponse")]
        string setCampus(int Id, string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setClass", ReplyAction="http://tempuri.org/IBusinessService/setClassResponse")]
        string setClass(Client.BusinessLayer.ClassData CD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setPromotion", ReplyAction="http://tempuri.org/IBusinessService/setPromotionResponse")]
        string setPromotion(int Id, string PromotionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setSubject", ReplyAction="http://tempuri.org/IBusinessService/setSubjectResponse")]
        string setSubject(Client.BusinessLayer.SubjectData SD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setPeriod", ReplyAction="http://tempuri.org/IBusinessService/setPeriodResponse")]
        string setPeriod(Client.BusinessLayer.PeriodData PD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/setEvent", ReplyAction="http://tempuri.org/IBusinessService/setEventResponse")]
        string setEvent(Client.BusinessLayer.EventData EditedEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delUser", ReplyAction="http://tempuri.org/IBusinessService/delUserResponse")]
        string delUser(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delCampus", ReplyAction="http://tempuri.org/IBusinessService/delCampusResponse")]
        string delCampus(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delClass", ReplyAction="http://tempuri.org/IBusinessService/delClassResponse")]
        string delClass(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delPromotion", ReplyAction="http://tempuri.org/IBusinessService/delPromotionResponse")]
        string delPromotion(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delSubject", ReplyAction="http://tempuri.org/IBusinessService/delSubjectResponse")]
        string delSubject(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delPeriod", ReplyAction="http://tempuri.org/IBusinessService/delPeriodResponse")]
        string delPeriod(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delRight", ReplyAction="http://tempuri.org/IBusinessService/delRightResponse")]
        string delRight(string UserName, string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/delEvent", ReplyAction="http://tempuri.org/IBusinessService/delEventResponse")]
        string delEvent(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getUser", ReplyAction="http://tempuri.org/IBusinessService/getUserResponse")]
        Client.BusinessLayer.UserData getUser(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getClass", ReplyAction="http://tempuri.org/IBusinessService/getClassResponse")]
        Client.BusinessLayer.ClassData getClass(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getPeriod", ReplyAction="http://tempuri.org/IBusinessService/getPeriodResponse")]
        Client.BusinessLayer.PeriodData getPeriod(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getSubject", ReplyAction="http://tempuri.org/IBusinessService/getSubjectResponse")]
        Client.BusinessLayer.SubjectData getSubject(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getEventsByCampus", ReplyAction="http://tempuri.org/IBusinessService/getEventsByCampusResponse")]
        Client.BusinessLayer.EventData[] getEventsByCampus(int CampusId, System.DateTime Start, System.DateTime Stop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/isUpToDateByCampus", ReplyAction="http://tempuri.org/IBusinessService/isUpToDateByCampusResponse")]
        bool isUpToDateByCampus(int Id, System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getEventsByUniversity", ReplyAction="http://tempuri.org/IBusinessService/getEventsByUniversityResponse")]
        Client.BusinessLayer.EventData[] getEventsByUniversity(System.DateTime Start, System.DateTime Stop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/isUpToDateByUniversity", ReplyAction="http://tempuri.org/IBusinessService/isUpToDateByUniversityResponse")]
        bool isUpToDateByUniversity(System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getEventsByPeriod", ReplyAction="http://tempuri.org/IBusinessService/getEventsByPeriodResponse")]
        Client.BusinessLayer.EventData[] getEventsByPeriod(int PeriodId, System.DateTime Start, System.DateTime Stop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/isUpToDateByPeriod", ReplyAction="http://tempuri.org/IBusinessService/isUpToDateByPeriodResponse")]
        bool isUpToDateByPeriod(int Id, System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getEventsByClass", ReplyAction="http://tempuri.org/IBusinessService/getEventsByClassResponse")]
        Client.BusinessLayer.EventData[] getEventsByClass(int ClassId, System.DateTime Start, System.DateTime Stop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/isUpToDateByClass", ReplyAction="http://tempuri.org/IBusinessService/isUpToDateByClassResponse")]
        bool isUpToDateByClass(int Id, System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getPrivateEvents", ReplyAction="http://tempuri.org/IBusinessService/getPrivateEventsResponse")]
        Client.BusinessLayer.EventData[] getPrivateEvents(System.DateTime Start, System.DateTime Stop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/isUpToDateByPrivate", ReplyAction="http://tempuri.org/IBusinessService/isUpToDateByPrivateResponse")]
        bool isUpToDateByPrivate(System.DateTime LastUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getCampusNames", ReplyAction="http://tempuri.org/IBusinessService/getCampusNamesResponse")]
        string[] getCampusNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getClassesNames", ReplyAction="http://tempuri.org/IBusinessService/getClassesNamesResponse")]
        string[] getClassesNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getPromotionsNames", ReplyAction="http://tempuri.org/IBusinessService/getPromotionsNamesResponse")]
        string[] getPromotionsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getPeriodsNames", ReplyAction="http://tempuri.org/IBusinessService/getPeriodsNamesResponse")]
        string[] getPeriodsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getSubjectsNames", ReplyAction="http://tempuri.org/IBusinessService/getSubjectsNamesResponse")]
        string[] getSubjectsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getUsersNames", ReplyAction="http://tempuri.org/IBusinessService/getUsersNamesResponse")]
        string[] getUsersNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getModalities", ReplyAction="http://tempuri.org/IBusinessService/getModalitiesResponse")]
        string[] getModalities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getCampusPeriodClassTree", ReplyAction="http://tempuri.org/IBusinessService/getCampusPeriodClassTreeResponse")]
        System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, string[]>> getCampusPeriodClassTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdCampusNames", ReplyAction="http://tempuri.org/IBusinessService/getIdCampusNamesResponse")]
        Client.BusinessLayer.IdName[] getIdCampusNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdClassesNames", ReplyAction="http://tempuri.org/IBusinessService/getIdClassesNamesResponse")]
        Client.BusinessLayer.IdName[] getIdClassesNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdPromotionsNames", ReplyAction="http://tempuri.org/IBusinessService/getIdPromotionsNamesResponse")]
        Client.BusinessLayer.IdName[] getIdPromotionsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdPeriodsNames", ReplyAction="http://tempuri.org/IBusinessService/getIdPeriodsNamesResponse")]
        Client.BusinessLayer.IdName[] getIdPeriodsNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdSubjectsNamesModality", ReplyAction="http://tempuri.org/IBusinessService/getIdSubjectsNamesModalityResponse")]
        System.Tuple<Client.BusinessLayer.IdName, string>[] getIdSubjectsNamesModality();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdUsersNames", ReplyAction="http://tempuri.org/IBusinessService/getIdUsersNamesResponse")]
        Client.BusinessLayer.IdName[] getIdUsersNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/getIdCampusPeriodClassTree", ReplyAction="http://tempuri.org/IBusinessService/getIdCampusPeriodClassTreeResponse")]
        System.Collections.Generic.Dictionary<Client.BusinessLayer.IdName, System.Collections.Generic.Dictionary<Client.BusinessLayer.IdName, Client.BusinessLayer.IdName[]>> getIdCampusPeriodClassTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addUser", ReplyAction="http://tempuri.org/IBusinessService/addUserResponse")]
        string addUser(string UserName, string UserPassword, string UserClassName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addCampus", ReplyAction="http://tempuri.org/IBusinessService/addCampusResponse")]
        string addCampus(string CampusName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/addClass", ReplyAction="http://tempuri.org/IBusinessService/addClassResponse")]
        string addClass(string ClassName, string CampusName, string PeriodeName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusinessServiceChannel : Client.BusinessLayer.IBusinessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessServiceClient : System.ServiceModel.ClientBase<Client.BusinessLayer.IBusinessService>, Client.BusinessLayer.IBusinessService {
        
        public BusinessServiceClient() {
        }
        
        public BusinessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addPromotion(string PromotionName) {
            return base.Channel.addPromotion(PromotionName);
        }
        
        public string addSubject(string SubjectName, int Hours, string Modality) {
            return base.Channel.addSubject(SubjectName, Hours, Modality);
        }
        
        public string addPeriod(string PeriodName, string PromotionName, System.DateTime PeriodStart, System.DateTime PeriodEnd) {
            return base.Channel.addPeriod(PeriodName, PromotionName, PeriodStart, PeriodEnd);
        }
        
        public string grantNewRight(string UserName, string CampusName) {
            return base.Channel.grantNewRight(UserName, CampusName);
        }
        
        public string addEventToCampus(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string CampusName, string Place) {
            return base.Channel.addEventToCampus(EventName, Start, End, Mandatory, SpeakerName, CampusName, Place);
        }
        
        public string addEventToPeriode(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string PeriodeName, string Place) {
            return base.Channel.addEventToPeriode(EventName, Start, End, Mandatory, SpeakerName, PeriodeName, Place);
        }
        
        public string addEventToClass(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string ClassName, string Subject, string Modality, string Place) {
            return base.Channel.addEventToClass(EventName, Start, End, Mandatory, SpeakerName, ClassName, Subject, Modality, Place);
        }
        
        public string addEventToUniversity(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string SpeakerName, string Place) {
            return base.Channel.addEventToUniversity(EventName, Start, End, Mandatory, SpeakerName, Place);
        }
        
        public string addEventToUser(string EventName, System.DateTime Start, System.DateTime End, bool Mandatory, string Place) {
            return base.Channel.addEventToUser(EventName, Start, End, Mandatory, Place);
        }
        
        public string setUser(Client.BusinessLayer.UserData UD) {
            return base.Channel.setUser(UD);
        }
        
        public string setCampus(int Id, string CampusName) {
            return base.Channel.setCampus(Id, CampusName);
        }
        
        public string setClass(Client.BusinessLayer.ClassData CD) {
            return base.Channel.setClass(CD);
        }
        
        public string setPromotion(int Id, string PromotionName) {
            return base.Channel.setPromotion(Id, PromotionName);
        }
        
        public string setSubject(Client.BusinessLayer.SubjectData SD) {
            return base.Channel.setSubject(SD);
        }
        
        public string setPeriod(Client.BusinessLayer.PeriodData PD) {
            return base.Channel.setPeriod(PD);
        }
        
        public string setEvent(Client.BusinessLayer.EventData EditedEvent) {
            return base.Channel.setEvent(EditedEvent);
        }
        
        public string delUser(int Id) {
            return base.Channel.delUser(Id);
        }
        
        public string delCampus(int Id) {
            return base.Channel.delCampus(Id);
        }
        
        public string delClass(int Id) {
            return base.Channel.delClass(Id);
        }
        
        public string delPromotion(int Id) {
            return base.Channel.delPromotion(Id);
        }
        
        public string delSubject(int Id) {
            return base.Channel.delSubject(Id);
        }
        
        public string delPeriod(int Id) {
            return base.Channel.delPeriod(Id);
        }
        
        public string delRight(string UserName, string CampusName) {
            return base.Channel.delRight(UserName, CampusName);
        }
        
        public string delEvent(int Id) {
            return base.Channel.delEvent(Id);
        }
        
        public Client.BusinessLayer.UserData getUser(int ID) {
            return base.Channel.getUser(ID);
        }
        
        public Client.BusinessLayer.ClassData getClass(int ID) {
            return base.Channel.getClass(ID);
        }
        
        public Client.BusinessLayer.PeriodData getPeriod(int ID) {
            return base.Channel.getPeriod(ID);
        }
        
        public Client.BusinessLayer.SubjectData getSubject(int ID) {
            return base.Channel.getSubject(ID);
        }
        
        public Client.BusinessLayer.EventData[] getEventsByCampus(int CampusId, System.DateTime Start, System.DateTime Stop) {
            return base.Channel.getEventsByCampus(CampusId, Start, Stop);
        }
        
        public bool isUpToDateByCampus(int Id, System.DateTime LastUpdate) {
            return base.Channel.isUpToDateByCampus(Id, LastUpdate);
        }
        
        public Client.BusinessLayer.EventData[] getEventsByUniversity(System.DateTime Start, System.DateTime Stop) {
            return base.Channel.getEventsByUniversity(Start, Stop);
        }
        
        public bool isUpToDateByUniversity(System.DateTime LastUpdate) {
            return base.Channel.isUpToDateByUniversity(LastUpdate);
        }
        
        public Client.BusinessLayer.EventData[] getEventsByPeriod(int PeriodId, System.DateTime Start, System.DateTime Stop) {
            return base.Channel.getEventsByPeriod(PeriodId, Start, Stop);
        }
        
        public bool isUpToDateByPeriod(int Id, System.DateTime LastUpdate) {
            return base.Channel.isUpToDateByPeriod(Id, LastUpdate);
        }
        
        public Client.BusinessLayer.EventData[] getEventsByClass(int ClassId, System.DateTime Start, System.DateTime Stop) {
            return base.Channel.getEventsByClass(ClassId, Start, Stop);
        }
        
        public bool isUpToDateByClass(int Id, System.DateTime LastUpdate) {
            return base.Channel.isUpToDateByClass(Id, LastUpdate);
        }
        
        public Client.BusinessLayer.EventData[] getPrivateEvents(System.DateTime Start, System.DateTime Stop) {
            return base.Channel.getPrivateEvents(Start, Stop);
        }
        
        public bool isUpToDateByPrivate(System.DateTime LastUpdate) {
            return base.Channel.isUpToDateByPrivate(LastUpdate);
        }
        
        public string[] getCampusNames() {
            return base.Channel.getCampusNames();
        }
        
        public string[] getClassesNames() {
            return base.Channel.getClassesNames();
        }
        
        public string[] getPromotionsNames() {
            return base.Channel.getPromotionsNames();
        }
        
        public string[] getPeriodsNames() {
            return base.Channel.getPeriodsNames();
        }
        
        public string[] getSubjectsNames() {
            return base.Channel.getSubjectsNames();
        }
        
        public string[] getUsersNames() {
            return base.Channel.getUsersNames();
        }
        
        public string[] getModalities() {
            return base.Channel.getModalities();
        }
        
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, string[]>> getCampusPeriodClassTree() {
            return base.Channel.getCampusPeriodClassTree();
        }
        
        public Client.BusinessLayer.IdName[] getIdCampusNames() {
            return base.Channel.getIdCampusNames();
        }
        
        public Client.BusinessLayer.IdName[] getIdClassesNames() {
            return base.Channel.getIdClassesNames();
        }
        
        public Client.BusinessLayer.IdName[] getIdPromotionsNames() {
            return base.Channel.getIdPromotionsNames();
        }
        
        public Client.BusinessLayer.IdName[] getIdPeriodsNames() {
            return base.Channel.getIdPeriodsNames();
        }
        
        public System.Tuple<Client.BusinessLayer.IdName, string>[] getIdSubjectsNamesModality() {
            return base.Channel.getIdSubjectsNamesModality();
        }
        
        public Client.BusinessLayer.IdName[] getIdUsersNames() {
            return base.Channel.getIdUsersNames();
        }
        
        public System.Collections.Generic.Dictionary<Client.BusinessLayer.IdName, System.Collections.Generic.Dictionary<Client.BusinessLayer.IdName, Client.BusinessLayer.IdName[]>> getIdCampusPeriodClassTree() {
            return base.Channel.getIdCampusPeriodClassTree();
        }
        
        public string addUser(string UserName, string UserPassword, string UserClassName) {
            return base.Channel.addUser(UserName, UserPassword, UserClassName);
        }
        
        public string addCampus(string CampusName) {
            return base.Channel.addCampus(CampusName);
        }
        
        public string addClass(string ClassName, string CampusName, string PeriodeName) {
            return base.Channel.addClass(ClassName, CampusName, PeriodeName);
        }
    }
}
